LANG = {
    "ru": {
        "search": "Поиск",
        "compare": "Сравнение",
        "calculator": "Калькулятор",
        "rankings": "Рейтинги",
        "brawlers": "Бравлеры",
        "converter": "Конвертер",
        "random": "Случайный",
        "profile": "Профиль",
        "mini_game": "Мини-игра",
        "top_brawlers": "Топ бравлеров",
        "badge": "Бейдж",
        "input_tag": "Введи тег игрока",
        "find": "Найти",
        "player_not_found": "Игрок не найден",
        "psi": "Player Skill Index",
        "trophies": "Трофеи",
        "psi_desc": "система оценки скилла по 7 модулям",
        "psi_modules": "Модули PSI",
        "psi_radar": "Радар PSI",
        "brawlers_by_tier": "Бравлеры по тирам",
        "top10_brawlers": "Топ-10 бравлеров",
        "trophies_vs_power": "Трофеи vs Сила (все бравлеры)",
        "trophy_change": "Изменение трофеев (battlelog)",
        "summary": "Сводка",
        "all_brawlers": "Все бравлеры",
        "last_battles": "Последние бои",
        "mode": "Режим",
        "map": "Карта",
        "result": "Рез.",
        "power": "Сила",
        "rank": "Ранг",
        "skin": "Скин",
        "growth_points": "Точки роста",
        "vs_average": "Сравнение со средним игроком",
        "avg": "ср.",
        "total_brawlers": "Бравлеров",
        "max_power": "Макс. сила",
        "next_trophies": "До трофеев",
        "next_level": "До уровня",
        "remaining": "осталось",
        "export_png": "Экспорт PNG",
        "share": "Поделиться",
        "search_another": "Искать другого",
        "open_in_bot": "Открыть в боте",
        "recent": "Недавние",
        "top10psi": "Топ-10 PSI",
        "popular_brawlers": "Популярные бравлеры",
        "most_used": "Самые используемые бравлеры среди топ-игроков",
        "of_top": "из 10 топов",
        "no_data": "Недостаточно данных",
        "loading": "Загрузка...",
        "error": "Ошибка",
        "badge_constructor": "Конструктор PSI-бейджа",
        "badge_desc": "Создай свой бейдж для форумов и соцсетей",
        "settings": "Настройки",
        "color": "Цвет",
        "bg_color": "Фон",
        "size": "Размер",
        "style": "Стиль",
        "custom_text": "Свой текст",
        "show_on_badge": "Показать на бейдже",
        "name": "Имя игрока",
        "rank_name": "Ранг (Ranked)",
        "club_name": "Клуб",
        "praims": "Праймы (P1/P2/P3)",
        "brawlers_count": "Кол-во бравлеров",
        "progress_bar": "Прогресс-бар PSI",
        "generate": "Сгенерировать",
        "copy_link": "Копировать ссылку",
        "download_svg": "Скачать SVG",
        "preview": "Предпросмотр",
        "link_profile": "Свяжи аккаунт Telegram",
        "link_desc": "Свяжи аккаунт Telegram чтобы увидеть свои данные.",
        "open_bot": "Открой бота @BllsBrawlbot и нажми /profile",
        "telegram_btn": "Открыть бота",
        "user_profile": "Личный кабинет",
        "favorites": "Избранное",
        "friends": "Друзья",
        "history": "История поиска",
        "activity": "Лента друзей",
        "badges": "Достижения",
        "cards": "Карточки",
        "empty": "Пусто",
        "no_activity": "Нет активности",
        "no_badges": "Пока нет достижений",
        "no_cards": "Нет карточек",
        "selected_tag": "Выбранный тег",
        "not_selected": "не выбран",
        "analysis": "Анализ PSI",
        "current_praims": "Текущие праймы",
        "current_score": "Текущий счёт",
        "boost_p2": "Поднять 5 бравлеров до P2",
        "boost_p3": "Поднять 3 бравлеров до P3",
        "total_potential": "Общий потенциал",
        "recommendations": "Рекомендации",
        "max_possible_psi": "Максимально возможный PSI",
        "remaining_to_max": "Осталось до максимума",
        "who_stronger": "Кто круче?",
        "guess_psi": "Угадай у кого из двух случайных игроков PSI выше",
        "choose_this": "ВЫБРАТЬ ЭТОГО",
        "new_players": "Новые игроки",
        "play_again": "Играть ещё",
        "correct_answer": "Правильно!",
        "wrong_answer": "Неправильно!",
        "draw": "Ничья!",
        "max_trophies": "Макс трофеи",
        "level": "Уровень",
        "name_color": "Цвет имени",
        "current_rank": "Текущий ранг",
        "best_rank": "Лучший ранг",
        "best_season_rank": "Лучший за сезон",
        "qualification": "Квалификация",
        "wins_3v3": "Побед 3v3",
        "wins_solo": "Побед соло",
        "wins_duo": "Побед дуо",
        "robo_rumble": "Robo Rumble",
        "big_brawler": "Big Brawler",
        "prestige": "Престиж",
        "updated": "Обновлено",
        "all": "Все",
        "search_brawler": "Поиск бравлера...",
        "player1": "Игрок 1",
        "player2": "Игрок 2",
        "usage": "Используют",
        "player_n": "Игрок",
        "tag_to_id": "Тег игрока → ID",
        "id_to_tag": "ID → Тег игрока",
        "team_tag_to_id": "Тег команды → ID",
        "id_to_team_tag": "ID → Тег команды",
        "convert": "Конвертировать",
        "analyze": "Анализировать",
        "praims_boost": "Праймы: можно добавить",
        "praims_max": "Праймы: максимум достигнут",
        "ranked_boost": "Ranked: подними до",
        "top_boost": "Топ-мир: можно добавить",
        "quant_boost": "Колич.: повысь уровень/трофеи",
        "brawlers_to_p2": "Бравлеров до P2",
        "current_psi": "Текущий PSI",
        "visualization": "Визуализация модулей",
        "current_points": "Текущие баллы",
        "module": "Модуль",
        "points": "Баллы",
        "max": "Макс",
        "analysis_desc": "Анализ всех модулей PSI и потенциал роста",
        "praims_boost_title": "Буст праймов",
        "brawlers_to_p2_lower": "бравлеров до P2:",
        "brawlers_to_p3": "Поднять 3 бравлеров до P3:",
        "praims_short": "Праймы",
        "top_short": "Топ-мир",
        "veteran_short": "Ветеран",
        "quant_short": "Колич.",
        "qual_short": "Качеств.",
        "club_short": "Клуб",
        "members_count": "Участников",
        "requirements": "Требования",
        "trophies_lower": "трофеев",
        "members": "Участники",
        "role": "Роль",
        "calculate_psi": "Рассчитать PSI",
        "size_small": "Маленький (200x100)", "size_medium": "Средний (400x200)", "size_large": "Большой (600x300)",
        "style_modern": "Современный", "style_classic": "Классический", "style_minimal": "Минимальный",
        "input_tag_hint": "Введи тег и нажми Сгенерировать",
        "generate_first": "Сначала сгенерируй бейдж", "link_copied": "Ссылка скопирована!",
    },
    "en": {
        "search": "Search",
        "compare": "Compare",
        "calculator": "Calculator",
        "rankings": "Rankings",
        "brawlers": "Brawlers",
        "converter": "Converter",
        "random": "Random",
        "profile": "Profile",
        "mini_game": "Mini Game",
        "top_brawlers": "Top Brawlers",
        "badge": "Badge",
        "input_tag": "Enter player tag",
        "find": "Find",
        "player_not_found": "Player not found",
        "psi": "Player Skill Index",
        "trophies": "Trophies",
        "psi_desc": "7-module skill rating system",
        "psi_modules": "PSI Modules",
        "psi_radar": "PSI Radar",
        "brawlers_by_tier": "Brawlers by Tier",
        "top10_brawlers": "Top 10 Brawlers",
        "trophies_vs_power": "Trophies vs Power (all brawlers)",
        "trophy_change": "Trophy Change (battlelog)",
        "summary": "Summary",
        "all_brawlers": "All Brawlers",
        "last_battles": "Recent Battles",
        "mode": "Mode",
        "map": "Map",
        "result": "Result",
        "power": "Power",
        "rank": "Rank",
        "skin": "Skin",
        "growth_points": "Growth Points",
        "vs_average": "vs Average Player",
        "avg": "avg.",
        "total_brawlers": "Brawlers",
        "max_power": "Max Power",
        "next_trophies": "To trophies",
        "next_level": "To level",
        "remaining": "left",
        "export_png": "Export PNG",
        "share": "Share",
        "search_another": "Search another",
        "open_in_bot": "Open in Bot",
        "recent": "Recent",
        "top10psi": "Top 10 PSI",
        "popular_brawlers": "Popular Brawlers",
        "most_used": "Most used brawlers among top players",
        "of_top": "out of 10 top",
        "no_data": "Not enough data",
        "loading": "Loading...",
        "error": "Error",
        "badge_constructor": "PSI Badge Constructor",
        "badge_desc": "Create your badge for forums and social networks",
        "settings": "Settings",
        "color": "Color",
        "bg_color": "Background",
        "size": "Size",
        "style": "Style",
        "custom_text": "Custom Text",
        "show_on_badge": "Show on badge",
        "name": "Player Name",
        "rank_name": "Rank (Ranked)",
        "club_name": "Club",
        "praims": "Praims (P1/P2/P3)",
        "brawlers_count": "Brawlers count",
        "progress_bar": "PSI Progress Bar",
        "generate": "Generate",
        "copy_link": "Copy Link",
        "download_svg": "Download SVG",
        "preview": "Preview",
        "link_profile": "Link Telegram Account",
        "link_desc": "Link your Telegram account to see your data.",
        "open_bot": "Open @BllsBrawlbot and press /profile",
        "telegram_btn": "Open Bot",
        "user_profile": "Profile",
        "favorites": "Favorites",
        "friends": "Friends",
        "history": "Search History",
        "activity": "Friends Activity",
        "badges": "Achievements",
        "cards": "Cards",
        "empty": "Empty",
        "no_activity": "No activity",
        "no_badges": "No achievements yet",
        "no_cards": "No cards",
        "selected_tag": "Selected tag",
        "not_selected": "not selected",
        "analysis": "PSI Analysis",
        "current_praims": "Current Praims",
        "current_score": "Current Score",
        "boost_p2": "Boost 5 brawlers to P2",
        "boost_p3": "Boost 3 brawlers to P3",
        "total_potential": "Total Potential",
        "recommendations": "Recommendations",
        "max_possible_psi": "Max Possible PSI",
        "remaining_to_max": "Remaining to Max",
        "who_stronger": "Who is stronger?",
        "guess_psi": "Guess which of the two random players has higher PSI",
        "choose_this": "CHOOSE THIS",
        "new_players": "New Players",
        "play_again": "Play Again",
        "correct_answer": "Correct!",
        "wrong_answer": "Wrong!",
        "draw": "Draw!",
        "max_trophies": "Max Trophies",
        "level": "Level",
        "name_color": "Name Color",
        "current_rank": "Current Rank",
        "best_rank": "Best Rank",
        "best_season_rank": "Best Season Rank",
        "qualification": "Qualification",
        "wins_3v3": "3v3 Wins",
        "wins_solo": "Solo Wins",
        "wins_duo": "Duo Wins",
        "robo_rumble": "Robo Rumble",
        "big_brawler": "Big Brawler",
        "prestige": "Prestige",
        "updated": "Updated",
        "all": "All",
        "search_brawler": "Search brawler...",
        "player1": "Player 1",
        "player2": "Player 2",
        "usage": "Usage",
        "player_n": "Player",
        "tag_to_id": "Player Tag → ID",
        "id_to_tag": "ID → Player Tag",
        "team_tag_to_id": "Team Tag → ID",
        "id_to_team_tag": "ID → Team Tag",
        "convert": "Convert",
        "analyze": "Analyze",
        "praims_boost": "Praims: can add",
        "praims_max": "Praims: max reached",
        "ranked_boost": "Ranked: rise to",
        "top_boost": "Top World: can add",
        "quant_boost": "Quant.: increase level/trophies",
        "brawlers_to_p2": "Brawlers to P2",
        "current_psi": "Current PSI",
        "visualization": "Module Visualization",
        "current_points": "Current Points",
        "module": "Module",
        "points": "Points",
        "max": "Max",
        "analysis_desc": "Analysis of all PSI modules and growth potential",
        "praims_boost_title": "Praims Boost",
        "brawlers_to_p2_lower": "brawlers to P2:",
        "brawlers_to_p3": "Boost 3 brawlers to P3:",
        "praims_short": "Praims",
        "top_short": "Top",
        "veteran_short": "Veteran",
        "quant_short": "Quant.",
        "qual_short": "Qual.",
        "club_short": "Club",
        "members_count": "Members",
        "requirements": "Requirements",
        "trophies_lower": "trophies",
        "members": "Members",
        "role": "Role",
        "calculate_psi": "Calculate PSI",
        "size_small": "Small (200x100)", "size_medium": "Medium (400x200)", "size_large": "Large (600x300)",
        "style_modern": "Modern", "style_classic": "Classic", "style_minimal": "Minimal",
        "input_tag_hint": "Enter tag and press Generate",
        "generate_first": "Generate badge first", "link_copied": "Link copied!",
    }
}
